science-gpt/science-gpt

.github/workflows/black.yml, .github/workflows/isort.yml, .gitignore, app.py, chunker/chunker.py, document/document.py, embeddings/embeddings.py, orchestrator/chat_orchestrator.py, orchestrator/utils.py, storage/text_storage.py, vectordb/database.py
I forgot to actually enable the linter checks in my last PR lol.
Enabled them here.
Since there were new changes that needed re-linting, I linted those as well.
=> Added linters

prompt_demo.ipynb
Just updating some output for the demo file
=> updated outputs

.gitignore, src/data_broker/data_broker.py, src/ingestion/vectordb.py
Vectorstore files are stored in the vectorstore directory hence the gitignore file
=> Made ChromaDB persistent

app.py, requirements.txt
Added a thumb up and down for each AI reply 
- Feedback is stored in st.session_state.messages
- Feedback is displayed in chat window
- streamlit-feedback package is used
- modularized some app.py code as needed
=> Feedback for each reply

app.py, src/configs/system_config.yaml, src/models/models.py, src/orchestrator/chat_orchestrator.py, src/orchestrator/config.py
added functionality for locally hosted models on macbook, needs to be cleaned up. please help.
=> Locallyhostedmodels

app.py, auth.py, src/configs/data_config.yaml, src/configs/user_config.yaml, src/data_broker/data_broker.py, src/ingestion/embedding.py
Cleaned up Embedding / RAG workflow in app - abstracting into databroker and embeddings
Changed behaviour so that embedding / RAG settings only available after selecting use RAG
Removed useless UI elements for now (i.e. connect / test model) - less clutter.
=> cleaned up code

app/src/data_broker/data_broker.py
allow for prompt instantiation with none config
=> Small bug fix

app/app.py
#42 #43 
Fixes these two issues
=> bug fix + QoL

app/app.py, app/src/ingestion/embedding.py
just added 2 more models. One more quantized than the other
=> added 2 openbio models

app/app.py, app/src/data_broker/data_broker.py, app/src/ingestion/chunking.py, app/src/ingestion/embedding.py
Collection name is updated according to embedding method and chunk size 
- collection is not regenerated unless there are new chunks
- multiple collections are created and generated on selection of a new combination
=> Swap between embedding + chunking chromadb - with caching

app/app.py, app/auth.py, app/src/configs/system_config.yaml, app/src/data_broker/data_broker.py, app/src/orchestrator/chat_orchestrator.py, app/src/prompt/retrieval.py
Fully Functioning User Knowledge Base Manager:
- File Upload - only adding new chunks
- File Deletion - only removing deleted file chunks
- Knowledge base RAG - double retrieval - once for each knowledge base
- Creates new data directory for user - creates new vectordb for the user and embedding settings
- Dynamic switch of knowledge base documents between embedding settings
=> Custom File Uploader

app/src/data_broker/data_broker.py, app/src/orchestrator/call_handlers.py, app/src/orchestrator/chat_orchestrator.py, app/src/orchestrator/utils.py, app/src/prompt/base_prompt.py, app/src/prompt/prompts.py, app/src/prompt/retrieval.py
=> Quality of Life with Cached Document Upload + Separate Rewritten Prompt from Query

app/src/orchestrator/chat_orchestrator.py, app/src/tests/databroker/test_databroker.py
More details [here](https://github.com/science-gpt/science-gpt/pull/58#discussion_r1853149654)
=> Fixed small bug with rewrite model param missing

README.md, app/src/databroker/databroker.py, app/src/ingestion/vectordb.py, app/src/tests/databroker/test_databroker.py, docker-compose-milvus.yaml
Three changes:
1. Added keyword search
2. Updated from v2.4 to v2.5
3. Switched to using milvus client instead of milvus collection
=> Milvus keyword support

docker-compose-milvus.yaml, docker-compose-sciencegpt.yaml, milvus.yaml
- Added restart policies to milvus containers
- Added the milvus configuration file to adjust the log level. Changed milvus logs to "error" from "info".
=> Docker milvus patches

app/app.py, app/src/configs/user_config.yaml, app/src/orchestrator/call_handlers.py, app/src/orchestrator/chat_orchestrator.py, app/src/prompt/retrieval.py, requirements.txt
DRAFT - changing the UI in the popout
=> neater chunk display in popout

app/app.py, app/src/configs/user_config.yaml, app/src/orchestrator/chat_orchestrator.py, app/src/prompt/retrieval.py
finishing up what was started with the chunk visualization
=> better query visualization

Dockerfile, docker-compose-milvus.yaml, docker-compose-sciencegpt.yaml
gpu cuda support for NC skus on azure
=> Updated docker buildfile and compose files to support nvidia gpu / cuda

Dockerfile, app/app.py, app/src/configs/system_config.yaml, app/src/databroker/databroker.py, app/src/ingestion/chunking.py, app/src/ingestion/embedding.py, docker-compose-milvus.yaml, docker-compose-sciencegpt.yaml, requirements.txt
tweaked docker build to better support nvidia GPU
swapped hugging face embedding model for bge
added data file list element in streamlit
=> Gpu support + fileviz

app/app.py, app/src/configs/system_config.yaml, app/src/ingestion/vectordb.py, milvus.yaml
added multiselect box
parsed string to remove file extension for now
increased nprob in milvus search
=> added multiselect box, parsed string to remove file extension for now

app/src/configs/system_config.yaml, app/src/logs/logger.py, app/src/orchestrator/chat_orchestrator.py, app/src/prompt/retrieval.py
=> making use of azure logs

app/src/databroker/databroker.py, app/src/ingestion/chunking.py, app/src/ingestion/vectordb.py
Fixed race condition causing multiple inserts on launch and upload
Added bootstrap to load chunks from database into cache on launch
=> fixed a bug and made caching better

app/app.py, app/src/configs/system_config.yaml, app/src/configs/user_config.yaml
quick fix to show the display on the keyword filtered retrieval page
=> Chunk-display-patch

.gitignore, app/app.py, app/src/configs/system_config.yaml, app/src/databroker/databroker.py, app/src/ingestion/embedding.py, app/src/ingestion/vectordb.py, app/src/orchestrator/config.py, app/src/prompt/retrieval.py, docker-compose-milvus.yaml
**PLS READ CAREFULLY FOR MY COMMENTS**
This is my first update primarily for **demo purposes**, and I’m looking for suggestions on how to structure **abstract classes** to better integrate with other existing embedding models.
- **`embedding.py`**:  
- Updated fields to include both **dense** and **sparse** vectors.  
- `docs` now stores a list of chunked text strings.  
- Added `BGEM3Embedder`, which utilizes `BGEM3EmbeddingFunction`.  
- **Ignore** the `random_embedding` function as it is not needed.
- **`vectordb.py`**:  
- Introduced `MilvusBGE_DB`, responsible for setting up **Milvus** (considering where this should be integrated within other files).  
- Implemented embedding insertion into MilvusDB, including **IDs, docs, sparse and dense vectors**.  
- Added **hybrid search** with …
=> implementing hybrid-search but needs to integrate into other existing classes structures/embedding models. 
